### ISSUE TITLE
Can't Access Commands on First Time Load

### ISSUE THREAD

**Issue by Desymoo** [EnderTurret/PatchedMod#1]
Hello! Thank you for this lovely utility, I've been happily patching away all of my biome frustrations since discovering it :)

The only issue I've ran into so far is the commands don't seem to be working on 1.19.2 forge, with only a few mods loaded. Here's what I've been trying:

1. Add ```"patched:has_patches": true``` to pack.mcmeta. 
(The wiki documentation also says something different by the way: ```"patched_has_patches": true```, which seemed to be incorrect)
2. Load the pack globally using Paxi. I've also tried loading it locally with the same results.
3. When I use the commands ```/patched list packs``` or ```/patchedc list packs``` they simply tell me that I have 0 packs with patches loaded.

The funny bit is that the patches still work fine, I just can't get it to list any information about them. Any insight would be greatly appreciated 🙏

**Comment by EnderTurret** [comment]
I can't seem to reproduce this issue, with or without Paxi. Could you attach (as a [gist](https://gist.github.com)) the `debug.log` file from when you ran those commands?

**Comment by Desymoo** [comment]
Oh interesting... It seems as though the commands start working after loading into the world for the second time onwards, they only fail during the first load into a new world. 

Here's the full [debug.log](https://gist.github.com/Desymoo/504a589fba2cc98d18d12f3b95e6237d). This includes the failed attempt on a new world followed by a successful one after exiting and reloading.

**Comment by EnderTurret** [comment]
I've managed to reproduce the issue by putting the datapack in before creating the world (via the "Data Packs" button in the world creation screen). The issue has to do with the datapack not being "initialized" from Patched's perspective, which it's supposed to be the moment anything is patched. If you have Patched dump the contents of a patched file (via `/patched dump file ...`), it'll initialize the datapack and then `/patched list packs` will work as expected.

My guess is that the create world screen reloads the datapacks when adding them, and then after the world is created recreates the datapack instances *without reloading any data*. This would explain why Patched doesn't think the datapack has patching enabled.

I'll look into a fix some more later, but for now you can workaround the problem by either reopening the world, doing `/reload`, or having Patched dump a file.
