### ISSUE TITLE
[Question] Is it possible to move an object to a property of itself?

### ISSUE THREAD

**Issue by SettingDust** [EnderTurret/PatchedMod#16]
Like below
```json
{
  "a": {
    "b": 1
  }
}
```
to
```json
{
  "a": {
    "c": {
      "b": 1
    }
  }
}
```
Move the `a` to `a.c`

**Comment by EnderTurret** [comment]
I believe the following should work:
```json
[
  {
    "op": "move",
    "from": "/a",
    "path": "/_temp"
  },
  {
    "op": "add",
    "path": "/a",
    "value": {}
  },
  {
    "op": "move",
    "from": "_temp",
    "path": "/a/c"
  }
]
```

**Comment by SettingDust** [comment]
Error.

![图片](https://github.com/EnderTurret/PatchedMod/assets/19922286/1e0768cf-21e1-4b35-9c1a-bb66a7cca4a9)

`TraversalException: /elements/0/element/delegate: No such child delegate`

**Comment by SettingDust** [comment]
Oh. It's working. Forget to remove the generated before
