### ISSUE TITLE
Crash when enabling Programmer Art resource pack on Fabric 1.20.1 version

### ISSUE THREAD

**Issue by minh-craft** [EnderTurret/PatchedMod#21]
Hi, 
First off, just wanted to say this mod concept is amazing, this is going to be so useful. Thank you for creating this!

I noticed an issue where this mod will crash when the Programmer Art resource pack is enabled. This issue doesn't seem to exist on the Forge 1.20.1 version of this mod. 
I tested with creating a fresh Minecraft 1.20.1 install with just Fabric and Patched installed. The crash happens when Programmer Art is enabled. Afterwards, the game will continue crashing until Patched is disabled, the game is loaded up again, and Programmer Art is disabled. 

Here's the crash logs:
[latest.log](https://github.com/user-attachments/files/17466410/latest.log)

**Comment by EnderTurret** [comment]
This should now be fixed as of `3.3.1+1.20.1`.
